apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-auth
  namespace: prod
type: kubernetes.io/dockerconfigjson
data:
  # Base64 encoded: {"auths":{"docker-registry.eltrue":{"username":"stan","password":"Qqquen2121","auth":"c3RhbjpRcXF1ZW4yMTIx"}}}
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXItcmVnaXN0cnkuZWx0cnVlIjp7InVzZXJuYW1lIjoic3RhbiIsInBhc3N3b3JkIjoiUXFxdWVuMjEyMSIsImF1dGgiOiJjM1JoYmpwUmNYRjFaVzR5TVRJeCJ9fX0=
